version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
  build:
    commands:
      - docker build --tag "${REPOSITORY}:${TAG}"   .
  
  post_build:
    commands:
       - docker push "${REPOSITORY}:${TAG}"
       - printf '{"Image":"%s:%s"}' $REPOSITORY $TAG > build.json      
   