version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-2)
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build --build-arg KEY=$AWS_KEY --build-arg SECRET=$AWS_SECRET -t $REPOSITORY:latest .
      - docker tag $REPOSITORY:latest $REPOSITORY:$IMAGE_TAG
  
  post_build:
    commands:
       - echo Build completed on `date`
       - echo Pushing the Docker images...
       - docker push $REPOSITORY:latest
       - docker push $REPOSITORY:$IMAGE_TAG
       - printf '[{"name":"docker-secret","imageUri":"%s"}]' $REPOSITORY:$IMAGE_TAG > build.json   
       - cat build.json
artifacts:
    files:
       - build.json
    discard-paths: yes
