Parameters:
  Cluster:
     Type: String
  DesiredCount:
     Type: String
  Image:
      Type: String
  Role:
      Type: String
  TargetGroupArn:
      Type: String

Resources:
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: !Ref DesiredCount
      Role: !Ref Role
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
         - ContainerName: node
           ContainerPort: 8080
           TargetGroupArn: !Ref TargetGroupArn

  TaskDefinition:
     Type: AWS::ECS::TaskDefinition
     Properties:
       Family: Service
       ContainerDefinitions:
          - Name: node
            Image: !Ref Image
            Memory: 512
            PortMappings:
              - ContainerPort: 80  

